---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

# Creating a scatter plot

Together with your group, you will create a scatter plot to display the relationship between two variables in your data (an x and a y variable).

To do this, each member of your team will be responsible for writing a piece of the code to draw the plot. Then, you'll pull each piece of code together in this notebook to make a scatter plot function.


## Setup


First, we'll import the functions to draw using the turtle libray.

(Here, I'm also importating from random to make a database but the students will have real data)

```{python}
from turtle import *
import pandas as pd
```

Next, we need to define some aspects of the scatterplot we'll be drawing:
   - **origin_screen_x** - the x-coordinate on the turtle screen where the plot origin will be drawn
   - **origin_screen_y** - the x-coordinate on the turtle screen where the plot origin will be drawn
   - **x_axis_length** - the width of the plot
   - **y_axis_length** - the height of the plot
   - **x_axis_domain** - the domain that the plot's x-axis will span
   - **x_axis_increment** - the space between each tick mark on the x-axis
   - **y_axis_domain** - the domain that the plot's y-axis will span
   - **y_axis_increment** - the space between each tick mark on the y-axis
   - **tick_size** - the size of the tick mark on the axes

Every function you write will need to use these settings so that the function can draw a scatter plot with any of these settings changed.

```{python}
plot_settings = {
    'origin_screen_x': -100,
    'origin_screen_y': -100,
    'x_axis_length': 300,
    'y_axis_length': 300,
    'x_axis_domain': (0,1439),
    'x_axis_increment': 120,
    'y_axis_domain': (26,32),
    'y_axis_increment': 1,
    'tick_size': 4
}
```

Additionally, to help you manage your data, we've provided you with this function to "clamp" your data so that it will always fall within the boundaries of the x- and y- axis of your plot.

```{python}
def clamp_point(x, domain):
    if x < domain[0]:
        return domain[0]
    if x > domain[1]:
        return domain[1]
    return x

def clamp_database(db):
    x_axis_low = plot_settings['x_axis_domain'][0]
    y_axis_low = plot_settings['y_axis_domain'][0]
    x_axis_high = plot_settings['x_axis_domain'][1]
    y_axis_high = plot_settings['y_axis_domain'][1]
    
    x_domain = (x_axis_low, x_axis_high)
    y_domain = (y_axis_low, y_axis_high)
    for i in range(len(db)):
        x_clamp = clamp_point(db.iloc[i][0], x_domain)
        y_clamp = clamp_point(db.iloc[i][1], y_domain)
        db.iloc[i, 0] = x_clamp
        db.iloc[i, 1] = y_clamp
    return db
```

## Your functions

Since this is your first time working on a task this large, we've already decomposed the program into the following functions (described more below):
   - `scale(x, old_domain, new_domain)`
   - `draw_axis(ax)`
   - `plot_point(db)`

🛑 👀 🛑 **Before you start writing your function(s), make sure to read over this outline as a whole so you know how your function will be expected to interact with the other functions.**

Code is like a jigsaw puzzle: if you're piece doesn't fit correctly, the big picture can't come together.


### 💻 scale( )

One of the more conceptually difficult challenges of this program will be translating between the coordinates of the scatter plot \[the (x,y) coordinates from your data\] and the coordinates of the screen where the turtle draws \[the (x,y) coordinates you will give the turtle\].

To help make this translation easier, one member of your group will write a function that takes a number `x` that falls between the lower and upper bounds of `old_domain` and scales it so that is falls in the same place between the lower and upper bounds of `new_domain`.

For example, say you have a scatter plot with width and height 100. However, you only want your x- and y-axis to span from 0 to 10. `Scale` should translate points that fall from 0-10 to fall in the same way from 0-100. So, scaling 5 would give you 50, 7 would get you 70, etc.

For the `scale()` function, the `old_domain` and `new_domain` parameters will be the tuple `(*low_end*, *high_end*)`. So, to access the low end of the old domain, you would use `old_domain[0]` and to access the high end of the new domain you would use `new_domain[1]`.

```{python}
def scale(x, old_domain, new_domain):

    return new_x
```

### 💻 draw_x_axis( ) and draw_y_axis( )

These functions are responsible for drawing the x- and y- axis of the scatter plot along with tick marks marking the distance. We've group these functions together because they will be very similar (but with a few important differences). 

To accomplish this task, you'll need to think about how to draw tick marks that are distanced based on the size of the plot but that represent increments relative to the domain of the axis. For example, say your axis has a length of 100 turtle distance units and a domain between 0-10. If you wanted to draw ticks for each integer in the domain (0, 1, 2, ..., 10), you would need to draw 11 ticks each spaced 10 turtle distance units apart.

To help you out, we've written two helper functions:

* `draw_tick( )` draws a tick of `tick_size` (defined in the settings dictionary) centered at the turtle's current location and parallel to the direction the turtle is facing.

* `label_tick(num)` takes an integer `num` and adds a label `5*tick_size` ahead of the turtle's current location and heading.

```{python}
def draw_tick():
    pendown()
    forward(plot_settings['tick_size']/2)
    backward(plot_settings['tick_size'])
    forward(plot_settings['tick_size']/2)
    penup()
```

```{python}
def label_tick(num):
    forward(plot_settings['tick_size']*5)
    write("{}".format(num), move=False, align="center", font=("Arial", 8, "normal"))
    backward(plot_settings['tick_size']*5)
```

```{python}
def draw_x_axis():

```

```{python}
def draw_y_axis():

```

### 💻 plot_points( )

Finally, you will need to actually plot the points on the scatter plot. This will consist of going through each point in your database and determining what each point's location will be on the turtle screen.

You will recieve data in a list variable, `data_points_list`, which is a list of `(x, y)` data points. You can access the x and y data points like this:
    
    data_point = data_points_list[0] #This takes the 0th data point from the list
    
    x = data_point[0]
    y = data_point[1]

You can assume that your teammates will provide you with a scale function described above. This will be helpful when determing what a point's scaled values will be, but you will need to figure out what domain you need to scale from and what domain you will scale to.

To help you out, we've pulled out another function `make_cross()` which should be useful which will draw a cross in the turtle's current position.

```{python}
def make_cross():
    pendown()
    pencolor('blue')
    setheading(0)
    for i in range(2):
        forward(plot_settings['tick_size']/2)
        backward(plot_settings['tick_size'])
        forward(plot_settings['tick_size']/2)
        right(90)
    penup()
```

```{python}
def plot_points(data_points_list):

```

## Putting together the puzzle

Once all of your teammates ahve contributed their code to the notebook, you can run the code cell below which defines a function to put each piece of the plot together.

```{python}
def draw(data_points_list):
    clearscreen()
    speed(0)
    draw_x_axis()
    draw_y_axis()
    plot_points(data_points_list)
    hideturtle()
```

## Accessing the data

Now that we've got all the functions we need to draw the scatter plot, all we need to do is pass some data into those functions.

**Don't worry too much about this code right now.** We'll go over it in depth later. 

For now, all you need to know is that the file containing the data you want to use should be a `.csv` file. You pass the file path as a string into the `.read_csv()` function (currently the file path is `ISF_air_pollution_dataset.csv`).

```{python}
df = pd.read_csv('ISF_air_pollution_dataset.csv',';')

df
```

Then, you chose which two columns of the data you want to use by putting names of the columns as strings into the `df[[]]` access operator. Currently, we're using the `Time` and `Temperature` columns of our dataset.

Here, we're also transforming the data to make it easier to work with. Specifically, we're changing the time stamp column to be minutes after 9:00 am and we're cutting out some of the data to make the Turtle draw faster.

*NOTE: This code cell may give you a warning when you run it. That's ok, it's just letting us know that we're changing the data in the data structure which is exactly what we want to do.*

```{python}
df_two_col = df[['Time', 'Temperature']]
for i in range(len(df_two_col)):
    df_two_col.iloc[i,0] = i%(60*24)
df_two_col = df_two_col.drop([i for i in range(len(df_two_col)) if i%60 != 0 and i%60 != 29])


df_two_col
```

Next, we'll use the `clamp_database()` function to make sure all of our data falls within the domain of the chart we want to draw.

*NOTE: This code cell may give you a warning when you run it. That's ok, it's just letting us know that we're changing the data in the data structure when we call the `clamp_database()` function which is exactly what we want to do.*

```{python}
df_two_col_clamp = clamp_database(df_two_col)
```

Finally, we need to change the data into a structure you're familiar with. Currently, it's in a dataframe, something we'll talk about more later.

For now, we'll put the data in a list, `data_points_list` as `(x, y)` pairs.

```{python}
data_points_list = [(x,y) for x, y in df_two_col_clamp.values]
data_points_list
```

## Make the scatter plot

Finally, after all our hard work, we can make the scatterplot!

```{python}
draw(data_points_list)
```

When you're ready to close the Turtle window, you can run the following code cell:

```{python}
bye()
```

```{python}

```
